apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reddit-autoposter
  name: reddit-autoposter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-autoposter
  template:
    metadata:
      labels:
        app: reddit-autoposter
      namespace: reddit-autoposter
      name: reddit-autoposter
    spec:
      containers:
        - name: reddit-autoposter
          image: ghcr.io/leemartin77/reddit_autoposter:e82cf2e0429b40b53e5be3ed15a4aa8617a9d600
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 8080
          # volumeMounts:
          #   - name: images-dir
          #     mountPath: /imgprssr
          env:
            - name: SQLITE_FILE
              value: ./sqlite
            - name: AUTH_ID
              value: xxx
            - name: AUTH_SECRET
              value: xxxx
            - name: AUTH_REDIRECTURL
              value: xxxxx
              # volumes:
              #   - name: images-dir
              #     persistentVolumeClaim:
              #       claimName: reddit-autoposter-imgprssr-pvc
