apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reddit-autoposter
  name: reddit-autoposter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-autoposter
  template:
    metadata:
      labels:
        app: reddit-autoposter
      namespace: reddit-autoposter
      name: reddit-autoposter
    spec:
      containers:
        - name: reddit-autoposter
          image: ghcr.io/leemartin77/reddit_autoposter:9cc709253a270c4ceb461825cea99d0ca9b4451f
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: storage-dir
              mountPath: /storage
          env:
            - name: SQLITE_FILE
              value: /storage/sqlite
            - name: AUTH_ID
              value: xxx
            - name: AUTH_SECRET
              value: xxxx
            - name: AUTH_REDIRECTURL
              value: xxxxx
      volumes:
        - name: storage-dir
          persistentVolumeClaim:
            claimName: reddit-autoposter-pvc
