version: 3


dotenv: ['.env']

tasks:
  dockerbuild:
    cmds:
      - docker buildx build --platform=linux/arm64/v8 .
  build:
    cmds:
      - CGO_ENABLED=1 go build -o dist/main cmd/webapp/main.go
  run:
    cmds:
      - CGO_ENABLED=1 go run cmd/webapp/main.go